name: Build EXE

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install
      run: pip install customtkinter matplotlib pyserial pyinstaller
    - name: Compile
      run: pyinstaller --noconsole --onefile main.py
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Windows_App_EXE
        path: dist/main.exe
